package com.example.rules

import java.util.List
import java.util.Arrays

import com.example.Values

rule "First Rule"
ruleflow-group "RFG-1"
    when
    	$v: Values()
    then
    	
    	System.out.println($v);
end


rule "Left Rule"
ruleflow-group "RFG-2"
    when
    	$v: Values( this == Values.LEFT )
    then
    	
    	System.out.println("Left Rule Fired");
end


rule "Right Rule"
ruleflow-group "RFG-3"
    when
    	$v: Values( this == Values.RIGHT )
    then
    	
    	System.out.println("Right Rule Fired");
end
