package com.example.rules

import java.util.*

import com.example.ClassWithValue
import com.example.Values

import org.slf4j.Logger;

rule "Rule 1"
no-loop true
ruleflow-group "RFG-1"
    when
    	$fact:	ClassWithValue()
    	$logger: Logger()
    then
    	$fact.setValue(null);
    	$logger.info("found");
    	
    	update($fact);
end

rule "Rule 2"
ruleflow-group "RFG-1"
    when
    	$fact:	ClassWithValue( valueIsNull )
    	$logger: Logger()
    then
    	$logger.debug("Found!");
end
